# Generated by Django 6.0.6 on 2026-06-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REVIEW', 'Review'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('reason', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_check', to='transactions.transaction')),
            ],
        ),
    ]
