# Generated by Django 6.0.6 on 2026-06-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_checks', '0002_alter_fraudcheck_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraudcheck',
            old_name='reason',
            new_name='reasons',
        ),
    ]
