# Generated by Django 6.0.6 on 2026-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_checks', '0003_rename_reason_fraudcheck_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcheck',
            name='ml_proba',
            field=models.FloatField(blank=True, help_text='ML probability from apply_ml_escalation (None = ML not called)', null=True),
        ),
    ]
