# Generated by Django 6.0.6 on 2026-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
    ]
